<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
</head>
<body>
    <!-- Image Map Generated by http://www.image-map.net/ -->
<img src="start.png" usemap="#image-map">

<map name="image-map">
    <area target="" alt="Log in" title="Log in" href="kategorier.php" coords="385,755,171,508" shape="rect">
</map>

HEJEHEJEHJ
</body>
</html>