<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
</head>
<body>
    
    <!-- Image Map Generated by http://www.image-map.net/ -->
<img src="kategorier.png" usemap="#image-map">

<map name="image-map">
    <area target="" alt="Havemaskiner" title="Havemaskiner" href="havemaskiner.php" coords="86,309,268,489" shape="rect">
    <area target="" alt="fuckpoul" title="fuckpoul" href="" coords="292,313,532,478" shape="rect">
</map>

</body>
</html>