<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
</head>
<body>
    
    <!-- Image Map Generated by http://www.image-map.net/ -->
<img src="./starkbilleder/kat.png" usemap="#image-map">


<map name="image-map">
    <area target="" alt="Havemaskiner" title="Havemaskiner" href="./havemaskiner.php" coords="56,199,182,328" shape="rect">
</map>


<?php 
session_start();
echo $_SESSION['id'];

?>

</body>
</html>